options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/palenkke-repo/palenkke:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/palenkke-repo/palenkke:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'palenkke'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/palenkke-repo/palenkke:$COMMIT_SHA'
      - '--port=8080'
      - '--region=us-central1'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/palenkke-repo/palenkke:$COMMIT_SHA'
